name: Deploy and Test API
# Install dependencies, run tests, if tests ok deploy on EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

      jobs:
        deploy:
          runs-on: ubuntu-latest
      
          steps:
            # Étape 1 : Checkout du repository (Sparse Checkout)
            - name: Checkout repository with sparse checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - run: |
                git sparse-checkout init --cone
                git sparse-checkout set api models tests data/processed --skip-checks
                echo "api/requirements_api.txt" >> .git/info/sparse-checkout
                echo "tests/requirements_tests.txt" >> .git/info/sparse-checkout
                git read-tree -mu HEAD
      
            # Étape 2 : Configurer Python 3.12.7
            - name: Set up Python 3.12.7
              uses: actions/setup-python@v2
              with:
                python-version: '3.12.7'
      
            # Étape 3 : Installer les dépendances des tests
            - name: Install Dependencies for Tests
              run: |
                python -m venv venv_tests
                source venv_tests/bin/activate
                pip install --upgrade pip
                pip install -r tests/requirements_tests.txt
      
            # Étape 4 : Vérifier la présence du modèle et des données
            - name: Verify model and data file existence
              run: |
                if [ ! -f "models/xgb_pipeline_tuned.pkl" ]; then
                  echo "Error: Model file xgb_pipeline_tuned.pkl not found!"
                  exit 1
                fi
                if [ ! -f "data/processed/test_feature_engineering_sample.csv" ]; then
                  echo "Error: Data file test_feature_engineering_sample.csv not found!"
                  exit 1
                fi
      
            # Étape 5 : Exécuter les tests de l'API
            - name: Run API Tests
              env:
                MODELS_DIR: models
              run: |
                source venv_tests/bin/activate
                pytest tests/test_api.py --maxfail=1 --disable-warnings -v
      