name: CI/CD Pipeline
act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.1.4']  

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 

      # 3. Installe les dépendances
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lance les tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=5 --disable-warnings -q
